version: '3.8'

services:
    php:
    image: mcr.microsoft.com/devcontainers/php:0-8.2
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "php -S 0.0.0.0:8000 -t src"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  db_data:
